# Generated by Django 3.2.13 on 2022-05-24 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(default='', max_length=15)),
                ('ad_name', models.CharField(default='', max_length=200)),
                ('ad_type', models.CharField(choices=[('sale', 'معروض للبيع'), ('rent', 'معروض للشراء')], default='', max_length=25)),
                ('amount', models.IntegerField(default=0)),
                ('ad_description', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('yhkaport', 'يهكابورل'), ('hathpack', 'هاتشباك'), ('sedan', 'سيدان')], default='', max_length=35)),
                ('company', models.CharField(choices=[('fiat', 'فيات'), ('hyundai', 'هيونداي'), ('chevrolet', 'شيفورليه'), ('toyota', 'تويوتا'), ('bmw', 'بي أم دبليو'), ('mercedes', 'مرسيدس'), ('nissan', 'نيسان'), ('kia', 'كيا')], default='', max_length=15)),
                ('fuel_type', models.CharField(choices=[('oil', 'ديزل'), ('electric', 'كهرباء'), ('gas', 'غاز طبيعى')], default='', max_length=35)),
                ('engine_capacity', models.CharField(choices=[('1400 - 1500', '1400 - 1500'), ('1600 - 1800', '1600 - 1800'), ('2000 - more', '2000 - more')], default='', max_length=35)),
                ('year', models.DateField()),
                ('color', models.CharField(choices=[('black', 'اسود'), ('silver', 'فضي'), ('blue', 'ازرق'), ('brouwn', 'بني'), ('gold', 'ذهبي'), ('red', 'نبيتي'), ('white', 'ابيض')], default='', max_length=35)),
                ('transmission_type', models.CharField(choices=[('manual', 'يدوي'), ('automatic', 'أوتوماتيك')], default='', max_length=35)),
                ('extra_features', models.CharField(choices=[('chair', 'مقاعد'), ('shpora', 'فوانيس شبورة'), ('speed', 'مثبت سرعة'), ('bluetouth', 'بولوتوث'), ('wheel', 'عجلات للطرق الوعرة'), ('navigation', 'نظام ملاحة'), ('FM', 'راديو اف ام'), ('Pillow', 'وسائد هوائية'), ('AC', 'تكييف'), ('USB', 'شاحن يو اس بى'), ('ceiling', 'فتحة سقف'), ('back camera', 'كاميرات خلفية'), ('Electric Glass', 'زجاج كهربى'), ('Leather seats', 'مقاعد جلد'), ('Electric mirrors', 'مرايا كهربائية'), ('center lock', 'سنتر لوك'), ('corner sensors', 'حساسات ركن'), ('leather', 'جلد')], default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bathrooms', 'حمامات'), ('bedrooms', 'غرف النوم'), ('dining rooms', 'غرف السفرة'), ('living rooms', 'غرف معيشة'), ('kitchen', 'مطبخ')], default='', max_length=35)),
                ('attach', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('general', 'عام'), ('car_sale', 'سيارات للبيع'), ('car_rent', 'سيارات للإيجار'), ('property_sale', 'عقارات للبيع'), ('property_rent', 'عقارات للإيجار'), ('mobile', 'موبايلات'), ('access', 'إكسسوارات'), ('midical', 'مستلزمات طبية'), ('electron', 'إكترونيات وأجهزة منزلية'), ('furniture', 'أثاث منزلي')], default='', max_length=35)),
                ('is_ad', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(choices=[('Iphone', 'ايفون'), ('Oppo', 'اوبو'), ('Samsung', 'سامسونج'), ('Huawei', 'هواوى'), ('Nokia', 'نوكيا'), ('Xiaomi', 'شاومى')], default='', max_length=200)),
                ('type', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Normal_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(default='', max_length=15)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=35)),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('price', models.CharField(choices=[('50000000 - more', '50000000 - أكثر'), ('10000000 - 50000000', '10000000 - 50000000'), ('5000000 - 10000000', '5000000 - 10000000'), ('1000000 - 5000000', '1000000 - 5000000'), ('500000 - 1000000', '500000 - 1000000')], default='', max_length=20)),
                ('type', models.CharField(choices=[('studio', 'ستوديو'), ('penthouse', 'بنتهاوس'), ('Duplex', 'دوبلكس'), ('villa', 'فيلا'), ('apartment', 'شقة')], default='', max_length=35)),
                ('furnished', models.BooleanField(default=False)),
                ('compound', models.CharField(choices=[('Highland Park', 'هاى لاند بارك'), ('High City', 'هاى سيتى'), ('granda', 'جراندا'), ('knoll', 'الربوة'), ('life', 'الحياه'), ('Mountain View iCity', 'ماونتن فيو اى سيتى'), ('my city', 'مدينتى')], default='', max_length=35)),
                ('amenities', models.CharField(choices=[('elevator', 'اسانسير'), ('natural gas', 'غاز طبيعى'), ('water meter', 'عداد مياه'), ('electricity meter', 'عداد كهرباء'), ('Swimming pool', 'حمام سباحة'), ('service room', 'غرفة خدمة'), ('security', 'امن'), ('private garden', 'حديقة خاصة'), ('kitchen appliances', 'اجهزة المطبخ'), ('Balcony', 'شرفة'), ('telephone', 'تليفون ارضى')], default='', max_length=35)),
                ('area', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Super_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=35)),
                ('password', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Vice_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=15)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=35)),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], default='', max_length=35)),
                ('mission', models.CharField(choices=[('Delete', 'مسح'), ('Update', 'تعديل'), ('All', 'الكل')], default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Properties_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('cash', 'كاش'), ('installment', 'تقسيط')], default='', max_length=35)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_term', models.CharField(choices=[('semi-finished', 'نصف تشطيب'), ('oysters and throats', 'محارة وحلوق'), ('ok without ch', 'طيببدون تش'), ('crossed out', 'متشطب')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Properties_Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('1000 - 3000', '1000 - 3000'), ('3000 - 5000', '3000 - 5000'), ('5000 - 10000', '5000 - 10000'), ('10000 - 20000', '10000 - 30000'), ('20000 - 30000', '10000 - 30000')], default='', max_length=15)),
                ('condition', models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], default='', max_length=35)),
                ('payment', models.CharField(choices=[('cash', 'كاش'), ('installment', 'تقسيط')], default='', max_length=35)),
                ('warranty', models.BooleanField(default=False)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('modile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('500 - 3000', '500 - 3000'), ('3000 - 10000', '3000 - 10000'), ('10000 - 20000', '10000 - 20000'), ('20000 - 50000', '20000 - 50000'), ('50000 - 200000', '50000 - 200000')], default='', max_length=15)),
                ('type', models.CharField(choices=[('teeth', 'الاسنان'), ('eyes', 'العيون'), ('spectrophotometer', 'المطياف الضوئى'), ('baby sitter', 'حاضنة الاطفال'), ('measurement of oxygen', 'قياس الاكسجين'), ('electrosurgery', 'الجراحة الكهربائى'), ('Ventilator', 'التنفس الصناعى'), ('dialysis', 'غسيل كلوى')], default='', max_length=35)),
                ('condition', models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('200 - 1000', '200 - 1000'), ('1000 - 5000', '1000 - 5000'), ('5000 - 10000', '5000 - 10000'), ('10000 - 30000', '10000 - 30000'), ('30000 - 50000', '30000 - 50000')], default='', max_length=15)),
                ('condition', models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('1000 - 5000', '1000 - 5000'), ('5000 - 10000', '5000 - 10000'), ('10000 - 20000', '10000 - 20000'), ('20000 - 50000', '20000 - 50000'), ('50000 - 100000', '50000 - 100000')], default='', max_length=15)),
                ('type', models.CharField(choices=[('microwave', 'مايكروويف'), ('cleaning devices', 'اجهزة نظافة'), ('furnaces', 'افران'), ('Deep Freezer', 'ديب فريزر'), ('adaptations', 'تكييفات'), ('screens', 'شاشات'), ('washers', 'غسالات'), ('fridg', 'ثلاجات')], default='', max_length=35)),
                ('condition', models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], default='', max_length=35)),
                ('brand', models.CharField(choices=[('sharp', 'شارب'), ('Samsung', 'سامسونج'), ('LG', 'ال جى'), ('kiriazi', 'كريازى'), ('Fresh', 'فريش'), ('Zanussi', 'زانوسى'), ('Toshiba', 'توشيبا')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('30000 - 100000', '30000 - 100000'), ('100000 - 300000', '100000 - 300000'), ('300000 - 500000', '300000 - 500000'), ('500000 - 1000000', '500000 - 1000000'), ('1000000 - 5000000', '1000000 - 5000000')], default='', max_length=20)),
                ('condition', models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], default='', max_length=35)),
                ('kilometer', models.CharField(choices=[('0 - 9999', '0 - 9999'), ('10000 - 39999', '10000 - 39999'), ('40000 - 70000', '40000 - 70000'), ('70000 - more', '70000 - اكثر')], default='', max_length=35)),
                ('ad_type', models.CharField(choices=[('sale', 'معروض للبيع'), ('rent', 'معروض للشراء')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('30000 - 100000', '30000 - 100000'), ('100000 - 300000', '100000 - 300000'), ('300000 - 500000', '300000 - 500000'), ('500000 - 1000000', '500000 - 1000000'), ('1000000 - 5000000', '1000000 - 5000000')], default='', max_length=20)),
                ('rental_period', models.CharField(choices=[('year', 'سنوى'), ('month', 'شهرى'), ('day', 'يومى')], default='', max_length=20)),
                ('rental_option', models.CharField(choices=[('advance', 'مقدم'), ('late', 'مأخر')], default='', max_length=15)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
        migrations.CreateModel(
            name='Access_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('200 - 500', '200 - 500'), ('500 - 1500', '500 - 1500'), ('1500 - 3000', '1500 - 3000'), ('3000 - 5000', '3000 - 5000'), ('5000 - 10000', '5000 - 10000')], default='', max_length=15)),
                ('type', models.CharField(choices=[('shoes', 'احذية'), ('bags', 'شنط'), ('glasses', 'نظارات'), ('Clothes', 'ملابس'), ('Hours', 'ساعات'), ('other', 'اخرى')], default='', max_length=35)),
                ('condition', models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
    ]
