# Generated by Django 4.0.4 on 2022-05-18 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('ad_name', models.CharField(max_length=200)),
                ('main_category', models.CharField(max_length=200)),
                ('ad_description', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=200)),
                ('ad_image', models.ImageField(upload_to='images/')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 51, 24, 504564, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=35)),
                ('payment_no', models.IntegerField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 51, 24, 504030, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Normal_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Super_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Vice_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=35)),
                ('mission', models.CharField(choices=[('Delete', 'Delete'), ('Update', 'Update'), ('All', 'All')], max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Properties_Sales',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[], max_length=35)),
                ('compound', models.CharField(choices=[], max_length=35)),
                ('furnished', models.CharField(choices=[], max_length=35)),
                ('amenities', models.CharField(choices=[], max_length=35)),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2022, 5, 18, 12, 51, 24, 506937, tzinfo=utc))),
                ('delivery_term', models.CharField(choices=[], max_length=35)),
                ('payment', models.CharField(choices=[], max_length=35)),
                ('area', models.CharField(max_length=10)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Properties_Rent',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[], max_length=35)),
                ('compound', models.CharField(choices=[], max_length=35)),
                ('furnished', models.CharField(choices=[], max_length=35)),
                ('amenities', models.CharField(choices=[], max_length=35)),
                ('area', models.CharField(max_length=10)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[], max_length=35)),
                ('condition', models.CharField(choices=[], max_length=35)),
                ('brand', models.CharField(choices=[], max_length=35)),
                ('payment', models.CharField(choices=[], max_length=35)),
                ('warranty', models.CharField(choices=[], max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Supplies',
            fields=[
                ('midical_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[], max_length=35)),
                ('condition', models.CharField(choices=[], max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_id', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('department', models.CharField(max_length=10)),
                ('condition', models.CharField(choices=[], max_length=35)),
                ('type', models.CharField(choices=[], max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Electonic_ad',
            fields=[
                ('electron_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[], max_length=35)),
                ('condition', models.CharField(choices=[], max_length=35)),
                ('brand', models.CharField(choices=[], max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Sales',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[], max_length=35)),
                ('model', models.CharField(choices=[], max_length=35)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(max_length=35)),
                ('color', models.CharField(choices=[], max_length=35)),
                ('year', models.DateField()),
                ('kilometer', models.IntegerField()),
                ('body_type', models.CharField(choices=[], max_length=35)),
                ('transmission_type', models.CharField(choices=[], max_length=35)),
                ('fuel_type', models.CharField(choices=[], max_length=35)),
                ('engine_capacity', models.CharField(choices=[], max_length=35)),
                ('extra_features', models.CharField(max_length=35)),
                ('ad_type', models.CharField(choices=[], max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Rent',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[], max_length=35)),
                ('model', models.CharField(choices=[], max_length=35)),
                ('price', models.IntegerField()),
                ('body_type', models.CharField(choices=[], max_length=35)),
                ('transmission_type', models.CharField(choices=[], max_length=35)),
                ('fuel_type', models.CharField(choices=[], max_length=35)),
                ('engine_capacity', models.CharField(choices=[], max_length=35)),
                ('rental_period', models.CharField(choices=[], max_length=35)),
                ('rental_option', models.CharField(choices=[], max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Access_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[], max_length=35)),
                ('condition', models.CharField(choices=[], max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
    ]
