# Generated by Django 3.2.13 on 2022-07-07 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='', max_length=10)),
                ('mission', models.CharField(choices=[('Delete', 'مسح'), ('Update', 'تعديل'), ('Admin', 'ادمن'), ('Normal', 'عادي')], default='Normal', max_length=35)),
                ('active_code', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(default='', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(default='', max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('يهكابورل', 'يهكابورل'), ('هاتشباك', 'هاتشباك'), ('سيدان', 'سيدان')], default='', max_length=35)),
                ('fuel_type', models.CharField(choices=[('ديزل', 'ديزل'), ('كهرباء', 'كهرباء'), ('غاز طبيعى', 'غاز طبيعى')], default='', max_length=35)),
                ('engine_capacity', models.IntegerField(default=0)),
                ('year', models.DateField()),
                ('color', models.CharField(choices=[('اسود', 'اسود'), ('فضي', 'فضي'), ('ازرق', 'ازرق'), ('بني', 'بني'), ('ذهبي', 'ذهبي'), ('نبيتي', 'نبيتي'), ('ابيض', 'ابيض')], default='', max_length=35)),
                ('transmission_type', models.CharField(choices=[('يدوي', 'يدوي'), ('أوتوماتيك', 'أوتوماتيك')], default='', max_length=35)),
                ('condition', models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35)),
                ('extra_features', multiselectfield.db.fields.MultiSelectField(choices=[('مقاعد', 'مقاعد'), ('فوانيس شبورة', 'فوانيس شبورة'), ('مثبت سرعة', 'مثبت سرعة'), ('بولوتوث', 'بولوتوث'), ('عجلات للطرق الوعرة', 'عجلات للطرق الوعرة'), ('نظام ملاحة', 'نظام ملاحة'), ('راديو اف ام', 'راديو اف ام'), ('وسائد هوائية', 'وسائد هوائية'), ('تكييف', 'تكييف'), ('شاحن يو اس بى', 'شاحن يو اس بى'), ('فتحة سقف', 'فتحة سقف'), ('كاميرات خلفية', 'كاميرات خلفية'), ('زجاج كهربى', 'زجاج كهربى'), ('مقاعد جلد', 'مقاعد جلد'), ('مرايا كهربائية', 'مرايا كهربائية'), ('سنتر لوك', 'سنتر لوك'), ('حساسات ركن', 'حساسات ركن'), ('جلد', 'جلد')], max_length=194)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('فيات', 'فيات'), ('هيونداي', 'هيونداي'), ('شيفورليه', 'شيفورليه'), ('تويوتا', 'تويوتا'), ('بي أم دبليو', 'بي أم دبليو'), ('مرسيدس', 'مرسيدس'), ('نيسان', 'نيسان'), ('كيا', 'كيا')], default='', max_length=35)),
                ('model', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('حمامات', 'حمامات'), ('غرف النوم', 'غرف النوم'), ('غرف السفرة', 'غرف السفرة'), ('غرف معيشة', 'غرف معيشة'), ('مطبخ', 'مطبخ')], default='', max_length=35)),
                ('attach', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('ايفون', 'ايفون'), ('اوبو', 'اوبو'), ('سامسونج', 'سامسونج'), ('هواوى', 'هواوى'), ('نوكيا', 'نوكيا'), ('شاومى', 'شاومى')], default='', max_length=200)),
                ('type', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('type', models.CharField(choices=[('ستوديو', 'ستوديو'), ('بنتهاوس', 'بنتهاوس'), ('دوبلكس', 'دوبلكس'), ('فيلا', 'فيلا'), ('شقة', 'شقة')], default='', max_length=35)),
                ('furnished', models.BooleanField(default=False)),
                ('compound', models.CharField(choices=[('هاى لاند بارك', 'هاى لاند بارك'), ('هاى سيتى', 'هاى سيتى'), ('جراندا', 'جراندا'), ('الربوة', 'الربوة'), ('الحياه', 'الحياه'), ('ماونتن فيو اى سيتى', 'ماونتن فيو اى سيتى'), ('مدينتى', 'مدينتى')], default='', max_length=35)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('اسانسير', 'اسانسير'), ('غاز طبيعى', 'غاز طبيعى'), ('عداد مياه', 'عداد مياه'), ('عداد كهرباء', 'عداد كهرباء'), ('حمام سباحة', 'حمام سباحة'), ('غرفة خدمة', 'غرفة خدمة'), ('امن', 'امن'), ('حديقة خاصة', 'حديقة خاصة'), ('اجهزة المطبخ', 'اجهزة المطبخ'), ('شرفة', 'شرفة'), ('تليفون ارضى', 'تليفون ارضى')], max_length=105)),
                ('area', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Properties_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('كاش', 'كاش'), ('تقسيط', 'تقسيط')], default='', max_length=35)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_term', models.CharField(choices=[('نصف تشطيب', 'نصف تشطيب'), ('محارة وحلوق', 'محارة وحلوق'), ('طيببدون تش', 'طيببدون تش'), ('متشطب', 'متشطب')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Properties_Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35)),
                ('payment', models.CharField(choices=[('كاش', 'كاش'), ('تقسيط', 'تقسيط')], default='', max_length=35)),
                ('warranty', models.BooleanField(default=False)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35)),
                ('type', models.CharField(choices=[('الاسنان', 'الاسنان'), ('العيون', 'العيون'), ('المطياف الضوئى', 'المطياف الضوئى'), ('حاضنة الاطفال', 'حاضنة الاطفال'), ('قياس الاكسجين', 'قياس الاكسجين'), ('الجراحة الكهربائى', 'الجراحة الكهربائى'), ('التنفس الصناعى', 'التنفس الصناعى'), ('غسيل كلوى', 'غسيل كلوى')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('logo', 'لوجو'), ('general', 'عام'), ('ad', 'إعلان'), ('featur_car', 'شركات مميزة سيارات'), ('car', 'سيارات'), ('featur_property', 'شركات مميزة عقارات'), ('property', 'عقارات'), ('featur_mobile', 'شركات مميزة موبايل'), ('mobile', 'موبايلات'), ('featur_access', 'شركات مميزة اكسسوارات'), ('access', 'إكسسوارات'), ('featur_midical', 'شركات مميزة طبية'), ('midical', 'مستلزمات طبية'), ('featur_electron', 'شركات مميزة إلكترونيات'), ('electron', 'إكترونيات وأجهزة منزلية'), ('featur_furniture', 'شركات مميزة أثاث'), ('furniture', 'أثاث منزلي')], default='', max_length=35)),
                ('payment_n', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('مايكروويف', 'مايكروويف'), ('اجهزة نظافة', 'اجهزة نظافة'), ('افران', 'افران'), ('ديب فريزر', 'ديب فريزر'), ('تكييفات', 'تكييفات'), ('شاشات', 'شاشات'), ('غسالات', 'غسالات'), ('ثلاجات', 'ثلاجات')], default='', max_length=35)),
                ('condition', models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35)),
                ('brand', models.CharField(choices=[('شارب', 'شارب'), ('سامسونج', 'سامسونج'), ('ال جى', 'ال جى'), ('كريازى', 'كريازى'), ('فريش', 'فريش'), ('زانوسى', 'زانوسى'), ('توشيبا', 'توشيبا')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.IntegerField(default=0)),
                ('ad_type', models.CharField(choices=[('معروض للبيع', 'معروض للبيع'), ('معروض للشراء', 'معروض للشراء')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_period', models.CharField(choices=[('سنوى', 'سنوى'), ('شهرى', 'شهرى'), ('يومى', 'يومى')], default='', max_length=20)),
                ('rental_option', models.CharField(choices=[('مقدم', 'مقدم'), ('مأخر', 'مأخر')], default='', max_length=15)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car_brand'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Access_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35)),
                ('type', models.CharField(choices=[('احذية', 'احذية'), ('شنط', 'شنط'), ('نظارات', 'نظارات'), ('ملابس', 'ملابس'), ('ساعات', 'ساعات'), ('اخرى', 'اخرى')], default='', max_length=35)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
            ],
        ),
    ]
