# Generated by Django 3.2.13 on 2022-07-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
