# Generated by Django 3.2.13 on 2022-06-07 20:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_sales',
            name='condition',
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('يهكابورل', 'يهكابورل'), ('هاتشباك', 'هاتشباك'), ('سيدان', 'سيدان')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('اسود', 'اسود'), ('فضي', 'فضي'), ('ازرق', 'ازرق'), ('بني', 'بني'), ('ذهبي', 'ذهبي'), ('نبيتي', 'نبيتي'), ('ابيض', 'ابيض')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='car',
            name='extra_features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('مقاعد', 'مقاعد'), ('فوانيس شبورة', 'فوانيس شبورة'), ('مثبت سرعة', 'مثبت سرعة'), ('بولوتوث', 'بولوتوث'), ('عجلات للطرق الوعرة', 'عجلات للطرق الوعرة'), ('نظام ملاحة', 'نظام ملاحة'), ('راديو اف ام', 'راديو اف ام'), ('وسائد هوائية', 'وسائد هوائية'), ('تكييف', 'تكييف'), ('شاحن يو اس بى', 'شاحن يو اس بى'), ('فتحة سقف', 'فتحة سقف'), ('كاميرات خلفية', 'كاميرات خلفية'), ('زجاج كهربى', 'زجاج كهربى'), ('مقاعد جلد', 'مقاعد جلد'), ('مرايا كهربائية', 'مرايا كهربائية'), ('سنتر لوك', 'سنتر لوك'), ('حساسات ركن', 'حساسات ركن'), ('جلد', 'جلد')], max_length=194),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('ديزل', 'ديزل'), ('كهرباء', 'كهرباء'), ('غاز طبيعى', 'غاز طبيعى')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('يدوي', 'يدوي'), ('أوتوماتيك', 'أوتوماتيك')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='car_brand',
            name='brand',
            field=models.CharField(choices=[('فيات', 'فيات'), ('هيونداي', 'هيونداي'), ('شيفورليه', 'شيفورليه'), ('تويوتا', 'تويوتا'), ('بي أم دبليو', 'بي أم دبليو'), ('مرسيدس', 'مرسيدس'), ('نيسان', 'نيسان'), ('كيا', 'كيا')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='rental_option',
            field=models.CharField(choices=[('مقدم', 'مقدم'), ('مأخر', 'مأخر')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='rental_period',
            field=models.CharField(choices=[('سنوى', 'سنوى'), ('شهرى', 'شهرى'), ('يومى', 'يومى')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car_sales',
            name='ad_type',
            field=models.CharField(choices=[('معروض للبيع', 'معروض للبيع'), ('معروض للشراء', 'معروض للشراء')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('حمامات', 'حمامات'), ('غرف النوم', 'غرف النوم'), ('غرف السفرة', 'غرف السفرة'), ('غرف معيشة', 'غرف معيشة'), ('مطبخ', 'مطبخ')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='electronic_ad',
            name='brand',
            field=models.CharField(choices=[('شارب', 'شارب'), ('سامسونج', 'سامسونج'), ('ال جى', 'ال جى'), ('كريازى', 'كريازى'), ('فريش', 'فريش'), ('زانوسى', 'زانوسى'), ('توشيبا', 'توشيبا')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='electronic_ad',
            name='condition',
            field=models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='electronic_ad',
            name='type',
            field=models.CharField(choices=[('مايكروويف', 'مايكروويف'), ('اجهزة نظافة', 'اجهزة نظافة'), ('افران', 'افران'), ('ديب فريزر', 'ديب فريزر'), ('تكييفات', 'تكييفات'), ('شاشات', 'شاشات'), ('غسالات', 'غسالات'), ('ثلاجات', 'ثلاجات')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='furniture_ad',
            name='condition',
            field=models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.CharField(choices=[('ايفون', 'ايفون'), ('اوبو', 'اوبو'), ('سامسونج', 'سامسونج'), ('هواوى', 'هواوى'), ('نوكيا', 'نوكيا'), ('شاومى', 'شاومى')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mobile_ad',
            name='condition',
            field=models.CharField(choices=[('مستعمل', 'مستعمل'), ('جديد', 'جديد')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='mobile_ad',
            name='payment',
            field=models.CharField(choices=[('كاش', 'كاش'), ('تقسيط', 'تقسيط')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='properties',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اسانسير', 'اسانسير'), ('غاز طبيعى', 'غاز طبيعى'), ('عداد مياه', 'عداد مياه'), ('عداد كهرباء', 'عداد كهرباء'), ('حمام سباحة', 'حمام سباحة'), ('غرفة خدمة', 'غرفة خدمة'), ('امن', 'امن'), ('حديقة خاصة', 'حديقة خاصة'), ('اجهزة المطبخ', 'اجهزة المطبخ'), ('شرفة', 'شرفة'), ('تليفون ارضى', 'تليفون ارضى')], max_length=105),
        ),
        migrations.AlterField(
            model_name='properties',
            name='compound',
            field=models.CharField(choices=[('هاى لاند بارك', 'هاى لاند بارك'), ('هاى سيتى', 'هاى سيتى'), ('جراندا', 'جراندا'), ('الربوة', 'الربوة'), ('الحياه', 'الحياه'), ('ماونتن فيو اى سيتى', 'ماونتن فيو اى سيتى'), ('مدينتى', 'مدينتى')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('ستوديو', 'ستوديو'), ('بنتهاوس', 'بنتهاوس'), ('دوبلكس', 'دوبلكس'), ('فيلا', 'فيلا'), ('شقة', 'شقة')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='properties_sales',
            name='delivery_term',
            field=models.CharField(choices=[('نصف تشطيب', 'نصف تشطيب'), ('محارة وحلوق', 'محارة وحلوق'), ('طيببدون تش', 'طيببدون تش'), ('متشطب', 'متشطب')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='properties_sales',
            name='payment',
            field=models.CharField(choices=[('كاش', 'كاش'), ('تقسيط', 'تقسيط')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='', max_length=10),
        ),
    ]
