# Generated by Django 4.0.4 on 2022-05-18 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 13, 0, 38, 839894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 13, 0, 38, 839348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties_sales',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 13, 0, 38, 842317, tzinfo=utc)),
        ),
    ]
