# Generated by Django 3.2.13 on 2022-07-11 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_advertisement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
