# Generated by Django 3.2.13 on 2022-06-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220607_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='payment_n',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('logo', 'لوجو'), ('general', 'عام'), ('ad', 'إعلان'), ('featur_car', 'شركات مميزة سيارات'), ('car', 'سيارات'), ('featur_property', 'شركات مميزة عقارات'), ('property', 'عقارات'), ('featur_mobile', 'شركات مميزة موبايل'), ('mobile', 'موبايلات'), ('featur_access', 'شركات مميزة اكسسوارات'), ('access', 'إكسسوارات'), ('featur_midical', 'شركات مميزة طبية'), ('midical', 'مستلزمات طبية'), ('featur_electron', 'شركات مميزة إلكترونيات'), ('electron', 'إكترونيات وأجهزة منزلية'), ('featur_furniture', 'شركات مميزة أثاث'), ('furniture', 'أثاث منزلي')], default='', max_length=35),
        ),
    ]
