# Generated by Django 3.2.13 on 2022-05-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mobile_mobile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brnad', models.CharField(choices=[('fiat', 'فيات'), ('hyundai', 'هيونداي'), ('chevrolet', 'شيفورليه'), ('toyota', 'تويوتا'), ('bmw', 'بي أم دبليو'), ('mercedes', 'مرسيدس'), ('nissan', 'نيسان'), ('kia', 'كيا')], default='', max_length=35)),
                ('model', models.CharField(default='', max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='company',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car_brand'),
        ),
    ]
