# Generated by Django 3.2.13 on 2022-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220608_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
