# Generated by Django 4.0.4 on 2022-05-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_advertisement_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_ad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='furniture_ad',
            name='id',
        ),
        migrations.AlterField(
            model_name='access_ad',
            name='access_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='car_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car_sales',
            name='car_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='electonic_ad',
            name='electron_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='furniture_ad',
            name='furniture_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medical_supplies',
            name='midical_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='properties_rent',
            name='property_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='properties_sales',
            name='property_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Payment_Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
    ]
