# Generated by Django 3.2.13 on 2022-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('car_sales', 'car_sales'), ('car_rent', 'car_rent'), ('property_sales', 'property_sales'), ('property_rent', 'property_rent'), ('mobile', 'mobile'), ('access', 'access'), ('midical', 'midical'), ('electron', 'electron'), ('furniture', 'furniture')], default='', max_length=200),
        ),
    ]
