# Generated by Django 3.2.13 on 2022-06-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advertisement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='payment_n',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
