# Generated by Django 3.2.13 on 2022-05-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220525_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Normal_User',
            new_name='User',
        ),
    ]
