# Generated by Django 3.2.13 on 2022-07-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advertisement_ad_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_sales',
            old_name='ad_type',
            new_name='offer_type',
        ),
    ]
