# Generated by Django 3.2.13 on 2022-07-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_ad_type_car_sales_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
