# Generated by Django 3.2.13 on 2022-05-26 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_normal_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_supplies',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='ad_description',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='email',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='car_rent',
            name='car',
        ),
        migrations.RemoveField(
            model_name='car_rent',
            name='rental_option',
        ),
        migrations.RemoveField(
            model_name='car_rent',
            name='rental_period',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car_rent',
            name='condition',
            field=models.CharField(choices=[('used', 'مستعمل'), ('new', 'جديد')], default='', max_length=35),
        ),
        migrations.AddField(
            model_name='car_rent',
            name='type',
            field=models.CharField(choices=[('shoes', 'احذية'), ('bags', 'شنط'), ('glasses', 'نظارات'), ('Clothes', 'ملابس'), ('Hours', 'ساعات'), ('other', 'اخرى')], default='', max_length=35),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='car',
            name='extra_features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('chair', 'مقاعد'), ('shpora', 'فوانيس شبورة'), ('speed', 'مثبت سرعة'), ('bluetouth', 'بولوتوث'), ('wheel', 'عجلات للطرق الوعرة'), ('navigation', 'نظام ملاحة'), ('FM', 'راديو اف ام'), ('Pillow', 'وسائد هوائية'), ('AC', 'تكييف'), ('USB', 'شاحن يو اس بى'), ('ceiling', 'فتحة سقف'), ('back camera', 'كاميرات خلفية'), ('Electric Glass', 'زجاج كهربى'), ('Leather seats', 'مقاعد جلد'), ('Electric mirrors', 'مرايا كهربائية'), ('center lock', 'سنتر لوك'), ('corner sensors', 'حساسات ركن'), ('leather', 'جلد')], max_length=163),
        ),
        migrations.AlterField(
            model_name='car_rent',
            name='price',
            field=models.CharField(choices=[('200 - 500', '200 - 500'), ('500 - 1500', '500 - 1500'), ('1500 - 3000', '1500 - 3000'), ('3000 - 5000', '3000 - 5000'), ('5000 - 10000', '5000 - 10000')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Access_ad',
        ),
        migrations.DeleteModel(
            name='Medical_Supplies',
        ),
    ]
