# Generated by Django 3.2.13 on 2022-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_advertisement_payment_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='payment_n',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
