# Generated by Django 3.2.13 on 2022-06-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_advertisement_payment_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile_ad',
            old_name='modile',
            new_name='mobile',
        ),
    ]
