# Generated by Django 3.2.13 on 2022-05-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
