# Generated by Django 3.2.13 on 2022-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220526_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='user',
            name='mission',
            field=models.CharField(choices=[('Delete', 'مسح'), ('Update', 'تعديل'), ('Admin', 'ادمن'), ('Normal', 'عادي')], default='Normal', max_length=35),
        ),
    ]
