# Generated by Django 3.2.13 on 2022-05-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220526_1841'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_ad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
